local Config = require("aidict.config")
local helpers = require("support.helpers")

describe("settings", function()
    it("falls back to the defaults when nothing was saved", function()
        local settings = helpers.settings()
        assert.are.equal(Config.DEFAULTS.cache_size, settings:get("cache_size"))
    end)

    it("ships no endpoint — it is baked into the package or set on the device", function()
        assert.are.equal("", Config.DEFAULTS.endpoint)
        local settings = helpers.settings()
        assert.are.equal("", settings:get("endpoint"))
        assert.is_false(settings:is_configured())
    end)

    it("is configured once an endpoint is set", function()
        local settings = helpers.settings({ endpoint = "https://gw.test/ai" })
        assert.is_true(settings:is_configured())
    end)

    it("returns what was saved", function()
        local settings = helpers.settings()
        assert.is_true(settings:set("endpoint", "https://example.test/ai"))
        assert.are.equal("https://example.test/ai", settings:get("endpoint"))
    end)

    it("refuses an endpoint that is not an http url", function()
        local settings = helpers.settings({ endpoint = "https://gw.test/ai" })
        local ok, reason = settings:set("endpoint", "example.test")
        assert.is_false(ok)
        assert.is_truthy(reason:find("URL"))
        assert.are.equal("https://gw.test/ai", settings:get("endpoint"))
    end)

    it("refuses unknown settings", function()
        local settings = helpers.settings()
        local ok, reason = settings:set("nonsense", 1)
        assert.is_false(ok)
        assert.is_truthy(reason:find("unknown setting"))
    end)

    it("refuses timeouts outside the sane range", function()
        local settings = helpers.settings()
        assert.is_false(settings:set("block_timeout", 0))
        assert.is_false(settings:set("block_timeout", 1000))
        assert.is_false(settings:set("block_timeout", "ten"))
        assert.is_true(settings:set("block_timeout", 15))
    end)

    it("refuses a negative cache", function()
        local settings = helpers.settings()
        assert.is_false(settings:set("cache_size", -1))
        assert.is_true(settings:set("cache_size", 0))
    end)

    it("takes prefetch only as a yes or a no", function()
        local settings = helpers.settings()
        assert.is_false(settings:get("prefetch"))
        assert.is_true(settings:set("prefetch", true))
        assert.is_true(settings:get("prefetch"))
        assert.is_false(settings:set("prefetch", "yes"))
        assert.is_false(settings:set("prefetch", 1))
    end)

    it("only knows two channels", function()
        local settings = helpers.settings()
        assert.is_true(settings:set("channel", "dev"))
        assert.is_false(settings:set("channel", "nightly"))
        assert.are.equal("dev", settings:get("channel"))
    end)

    it("ignores a stored value that no longer validates", function()
        -- e.g. a settings file edited by hand on the device
        local settings = helpers.settings({ block_timeout = -5, endpoint = 42 })
        assert.are.equal(Config.DEFAULTS.block_timeout, settings:get("block_timeout"))
        assert.are.equal(Config.DEFAULTS.endpoint, settings:get("endpoint"))
    end)

    it("accepts an empty api key as 'no key'", function()
        local settings = helpers.settings()
        assert.is_true(settings:set("api_key", ""))
        assert.are.equal("", settings:get("api_key"))
    end)

    it("resets a key back to its default", function()
        local settings = helpers.settings()
        settings:set("cache_size", 7)
        assert.is_true(settings:reset("cache_size"))
        assert.are.equal(Config.DEFAULTS.cache_size, settings:get("cache_size"))
    end)

    it("reports every setting from all()", function()
        local settings = helpers.settings({ cache_size = 42 })
        local all = settings:all()
        assert.are.equal(42, all.cache_size)
        for key in pairs(Config.DEFAULTS) do
            assert.is_not_nil(all[key])
        end
    end)

    it("passes flush through to the store", function()
        local store = helpers.store()
        local settings = require("aidict.settings").new(store)
        settings:flush()
        assert.are.equal(1, store.flushed)
    end)
end)
